### ISSUE TITLE
Do you plan to include DIGITS?

### ISSUE THREAD

**Issue by soumendra** [Miej/GoDeeper#7]
Thanks for the effort.

Do you plan to add DIGITS any time soon? https://developer.nvidia.com/digits

**Comment by itemize-mwoods** [comment]
It's already got DIGITS ;) 

'
System
...
NVIDIA DIGITS 5.1-dev
'

**Comment by Miej** [comment]
It's already got DIGITS ;) 
' 
System 
... 
NVIDIA DIGITS 5.1-dev 
'

**Comment by soumendra** [comment]
Aah, I see. It's not there in your list of available softwares, but it is mentioned elsewhere in the page.

Thanks.
